# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generalized_triangular_numbers_point <- function(z, n) {
    .Call(`_generalized_triangular_numbers_generalized_triangular_numbers_point`, z, n)
}

generalized_triangular_numbers_sequence <- function(z, n) {
    .Call(`_generalized_triangular_numbers_generalized_triangular_numbers_sequence`, z, n)
}

